<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Luft.Builder</RootNamespace>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lexer\Lexer.csproj" />
        <ProjectReference Include="..\Ast\Ast.csproj" />
        <ProjectReference Include="..\TypeChecker\TypeChecker.csproj" />
        <ProjectReference Include="..\Utility\Utility.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Runtime\aero_runtime.c" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LLVMSharp" Version="20.1.2" />
    </ItemGroup>

</Project>