<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Luft.Cli</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Builder\Builder.csproj" />
      <ProjectReference Include="..\Ast\Ast.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="test.aero" CopyToOutputDirectory="PreserveNewest"/>
      <Content Include="easytest.aero" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AeroLang.ACLI" Version="0.2.4" />
    </ItemGroup>

</Project>
